# Generated by Django 5.1.4 on 2025-12-22 02:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='센터명')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '지점(센터)',
                'verbose_name_plural': '지점(센터)',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='고객명')),
                ('phone', models.CharField(db_index=True, max_length=40, verbose_name='전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객',
                'indexes': [models.Index(fields=['phone', 'name'], name='core_custom_phone_50e021_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='번호판')),
                ('vin', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='차대번호(VIN)')),
                ('make', models.CharField(blank=True, max_length=80, verbose_name='제조사')),
                ('model', models.CharField(max_length=120, verbose_name='차량 모델')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='연식')),
                ('displacement_cc', models.PositiveIntegerField(blank=True, null=True, verbose_name='배기량(cc)')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='색상')),
                ('drive_type', models.CharField(choices=[('CHAIN', '체인'), ('BELT', '벨트'), ('SHAFT', '샤프트'), ('OTHER', '기타')], default='CHAIN', max_length=16, verbose_name='구동 방식')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.customer', verbose_name='고객')),
            ],
            options={
                'verbose_name': '차량',
                'verbose_name_plural': '차량',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='접수번호')),
                ('status', models.CharField(choices=[('RECEIVED', '접수'), ('IN_PROGRESS', '작업중'), ('WAITING_PARTS', '부품대기'), ('DONE', '완료'), ('RELEASED', '출고'), ('CANCELED', '취소')], default='RECEIVED', max_length=20, verbose_name='상태')),
                ('in_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='입고일시')),
                ('out_datetime', models.DateTimeField(blank=True, null=True, verbose_name='출고일시')),
                ('odometer_in', models.PositiveIntegerField(blank=True, null=True, verbose_name='입고 주행거리')),
                ('odometer_out', models.PositiveIntegerField(blank=True, null=True, verbose_name='출고 주행거리')),
                ('customer_complaint', models.TextField(blank=True, verbose_name='고객요청(증상)')),
                ('diagnosis', models.TextField(blank=True, verbose_name='진단')),
                ('work_detail', models.TextField(blank=True, verbose_name='작업내용')),
                ('recommendations', models.TextField(blank=True, verbose_name='권장사항')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='보증기한')),
                ('subtotal_parts', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='부품 소계')),
                ('subtotal_labor', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='공임 소계')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='할인')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='부가세')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.branch', verbose_name='지점(센터)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.vehicle', verbose_name='차량')),
            ],
            options={
                'verbose_name': '작업오더(접수)',
                'verbose_name_plural': '작업오더(접수)',
                'ordering': ['-in_datetime', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_name', models.CharField(max_length=160, verbose_name='공임 항목')),
                ('minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='시간(분)')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='금액')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor', to='core.workorder', verbose_name='작업오더')),
            ],
            options={
                'verbose_name': '작업 공임',
                'verbose_name_plural': '작업 공임',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CARD', '카드'), ('CASH', '현금'), ('TRANSFER', '계좌이체'), ('OTHER', '기타')], max_length=16, verbose_name='결제수단')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='금액')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='결제일시')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='비고')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.workorder', verbose_name='작업오더')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제',
            },
        ),
        migrations.CreateModel(
            name='WorkPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=160, verbose_name='부품/소모품명')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='단가')),
                ('line_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='금액')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.workorder', verbose_name='작업오더')),
            ],
            options={
                'verbose_name': '작업 부품',
                'verbose_name_plural': '작업 부품',
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate_no'], name='core_vehicl_plate_n_3ec62c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='core_vehicl_vin_167573_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['model'], name='core_vehicl_model_aa4ea5_idx'),
        ),
    ]
